TiendaVirtual_CarritoCompra/Models/Productos.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaVirtual_CarritoCompra.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    using System.Web.Mvc;

    public partial class Productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Productos()
        {
            this.PrecioUnidad = 0m;
        }

        public int Id { get; set; }

        [Required]
        [MaxLength(50, ErrorMessage = "Nombre demasiado largo. Máximo permitido 50 caracteres")]
        public string Nombre { get; set; }

        [Required]
        [Display(Name = "Descripción")]
        [MaxLength(150, ErrorMessage = "Descripción demasiada larga. Máximo permitido 150 caracteres")]
        public string Descripcion { get; set; }

        [DataType(DataType.Upload)]
        [Required(ErrorMessage = "Por favor seleccione una imagen.")]
        [Display(Name = "Imagen Producto")]
        public string PathImagen { get; set; }

        [DataType(DataType.Currency)]
        [Required]
        [Display(Name = "Precio Unidad")]
        public decimal PrecioUnidad { get; set; }

        [Range(0, 100)]
        [Required]
        public int Cantidad { get; set; }

        [Display(Name = "Categoría")]
        public virtual Categorias Categoria { get; set; }

        [Required(ErrorMessage = "Por favor seleccione una categoría.")]
        public int SelectedIdCategoria { get; set; }
        public SelectList SelectListCategorias { get; set; }

        public virtual Stocks Stock { get; set; }
    }
}

TiendaVirtual_CarritoCompra/Controllers/CarritoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TiendaVirtual_CarritoCompra.Models;

namespace TiendaVirtual_CarritoCompra.Controllers
{
    public class CarritoController : Controller
    {
        private TiendaVirtualCCEntities db = new TiendaVirtualCCEntities();

        private const int minCantidad = 2;

        // GET: CarritoCompra
        public ActionResult Index()
        {

            ViewBag.TotalProductos = SumaTotalProductosCarrito();
            return View((List<CarritoCompra>)HttpContext.Session["CARRITO"]);
        }

        // GET: Carrito/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            List<CarritoCompra> carritoCompra = (List<CarritoCompra>)HttpContext.Session["CARRITO"];
            int index = ExisteProductoEnCarrito(id);
            CarritoCompra carrito = carritoCompra[index];
            if (carrito == null)
            {
                return HttpNotFound();
            }
            return View(carrito);
        }

        // GET: Carrito/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            List<CarritoCompra> carritoCompra = (List<CarritoCompra>)HttpContext.Session["CARRITO"];
            int index = ExisteProductoEnCarrito(id);
            CarritoCompra carrito = carritoCompra[index];
            if (carrito == null)
            {
                return HttpNotFound();
            }
            return View(carrito);
        }


        // POST: Carrito/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            List<CarritoCompra> carritoCompra = (List<CarritoCompra>)HttpContext.Session["CARRITO"];
            int index = ExisteProductoEnCarrito(id);
            CarritoCompra carrito = carritoCompra[index];
            UpdateStockProductoRemoveCarrito(carrito);
            carritoCompra.Remove(carrito);
            if (carritoCompra.Any())
            {
                HttpContext.Session["CARRITO"] = carritoCompra;
            }
            else
            {
                HttpContext.Session["CARRITO"] = null;
            }           

            return RedirectToAction("Index");
        }

        // GET: Carrito
        public ActionResult Add(int id)
        {
            HttpSessionStateBase session = HttpContext.Session;

            string usuarioId = GetUsuarioId();
            CarritoCompra carrito = GetCarrito(id, usuarioId);

            if (session["CARRITO"] == null)
            {
                List<CarritoCompra> carritoCompra = new List<CarritoCompra>();
                carritoCompra.Add(carrito);
                session["CARRITO"] = carritoCompra;
            }
            else
            {
                List<CarritoCompra> carritoCompra = (List<CarritoCompra>)session["CARRITO"];
                int index = ExisteProductoEnCarrito(id);
                if (index != -1)
                {
                    carritoCompra[index].Cantidad++;
                    carritoCompra[index].PrecioTotal = carritoCompra[index].Cantidad * carritoCompra[index].Productos.PrecioUnidad;
                }
                else
                {
                    carritoCompra.Add(carrito);
                }
                session["CARRITO"] = carritoCompra;
            }

            UpdateStockProductoAddCarrito(id);

            return RedirectToAction("Index");
        }

        private void UpdateStockProductoAddCarrito(int id)
        {
            Productos productos = GetProductoById(id);
            productos.Cantidad = productos.Cantidad - 1;
            if (productos.Cantidad.Equals(minCantidad)) {
                Stocks stocks = new Stocks {
                    Productos = productos
                };                
                db.Stocks.Add(stocks);
                productos.Stock = stocks;
            }
            db.SaveChanges();
        }

        private void UpdateStockProductoRemoveCarrito(CarritoCompra carrito)
        {
            Productos productos = GetProductoById(carrito.Productos.Id);
            productos.Cantidad = productos.Cantidad + carrito.Cantidad;
            if (productos.Stock != null && productos.Cantidad > minCantidad)
            {                
                db.Stocks.Remove(productos.Stock);
                productos.Stock = null;
            }
            db.SaveChanges();
        }

        public CarritoCompra GetCarrito(int id, string usuarioId)
        {
            Random random = new Random();
            int idCarrito = random.Next(1, 1000);
            
            Productos producto = GetProductoById(id);
            return new CarritoCompra
            {
                Productos = producto,
                Id = idCarrito,
                FechaAlta = DateTime.Now,
                Cantidad = 1,
                UsuarioId = usuarioId,
                PrecioTotal = producto.PrecioUnidad * 1
            };

        }

        private Productos GetProductoById(int id)
        {
            return db.Productos.SingleOrDefault(
           p => p.Id == id);
        }

        private string GetUsuarioId()
        {
            HttpSessionStateBase session = HttpContext.Session;
            if (session["KEY_USER_ID"] == null)
            {
                if (!string.IsNullOrWhiteSpace(User.Identity.Name))
                {
                    session["KEY_USER_ID"] = User.Identity.Name;
                }
                else
                {
                    // Generate a new random GUID using System.Guid class.     
                    Guid tempCartId = Guid.NewGuid();
                    session["KEY_USER_ID"] = tempCartId.ToString();
                }
            }
            return session["KEY_USER_ID"].ToString();
        }

        private int ExisteProductoEnCarrito(int? id)
        {
            HttpSessionStateBase session = HttpContext.Session;
            List<CarritoCompra> carritoCompra = (List<CarritoCompra>)session["CARRITO"];
            for (int i = 0; i < carritoCompra.Count; i++)
            {
                if (carritoCompra[i].Productos.Id.Equals(id))
                    return i;
            }
            return -1;
        }

        private decimal SumaTotalProductosCarrito()
        {
            HttpSessionStateBase session = HttpContext.Session;
            decimal totalSuma = 0;
            List<CarritoCompra> carritoCompra = (List<CarritoCompra>)session["CARRITO"];
            for (int i = 0; carritoCompra != null && i < carritoCompra.Count; i++)
            {
                totalSuma = totalSuma + carritoCompra[i].PrecioTotal;
            }
            return totalSuma;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TiendaVirtual_CarritoCompra/Controllers/ProductosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TiendaVirtual_CarritoCompra.Models;

namespace TiendaVirtual_CarritoCompra.Controllers
{
    public class ProductosController : Controller
    {
        private TiendaVirtualCCEntities db = new TiendaVirtualCCEntities();

        // GET: Productos
        public ActionResult Index()
        {
            return View(db.Productos.ToList());
        }

        // GET: Productos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Productos productos = db.Productos.Find(id);
            if (productos == null)
            {
                return HttpNotFound();
            }
            return View(productos);
        }

        // GET: Productos/Create
        [Authorize(Users = "admin1@correo.es")]
        public ActionResult Create()
        {            
            SelectList lstCategoriasSelectList = new SelectList(db.Categorias, "Id", "Nombre");

            Productos producto = new Productos
            {
                SelectListCategorias = lstCategoriasSelectList
            };

            return View(producto);
        }
        
        // POST: Productos/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Users = "admin1@correo.es")]
        public ActionResult Create([Bind(Include = "Id,Nombre,Descripcion,PathImagen,PrecioUnidad,SelectedIdCategoria,Cantidad")] Productos productos)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (Request.Files.Count > 0)
                    {
                        var file = Request.Files[0];
                        if (file != null && file.ContentLength > 0)
                        {
                            var fileName = Path.GetFileName(file.FileName);
                            var path = Path.Combine(Server.MapPath("~/Content/Images"), fileName);
                            file.SaveAs(path);
                            productos.PathImagen = fileName;
                            ViewBag.FileStatus = "Imagen subida correctamente.";
                        }

                    }
                    
                }
                catch (Exception)
                {
                    ViewBag.FileStatus = "Error mientras se subía el fichero."; ;
                }
                productos.Categoria = db.Categorias.Find(productos.SelectedIdCategoria);                
                db.Productos.Add(productos);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(productos);
        }

        // GET: Productos/Edit/5
        [Authorize(Users = "admin1@correo.es")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Productos productos = db.Productos.Find(id);
            if (productos == null)
            {
                return HttpNotFound();
            }
            return View(productos);
        }

        // POST: Productos/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Users = "admin1@correo.es")]
        public ActionResult Edit([Bind(Include = "Id,Nombre,Descripcion,PrecioUnidad,Cantidad")] Productos productos)
        {
            Productos producto = db.Productos.Find(productos.Id);
            producto.Nombre = productos.Nombre;
            producto.Descripcion = productos.Descripcion;
            producto.PrecioUnidad = productos.PrecioUnidad;
            producto.Cantidad = productos.Cantidad;
            db.SaveChanges();
            return RedirectToAction("Index");     
        }

        // GET: Productos/Delete/5
        [Authorize(Users = "admin1@correo.es")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Productos productos = db.Productos.Find(id);
            if (productos == null)
            {
                return HttpNotFound();
            }
            return View(productos);
        }

        // POST: Productos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Users = "admin1@correo.es")]
        public ActionResult DeleteConfirmed(int id)
        {
            Productos productos = db.Productos.Find(id);
            db.Productos.Remove(productos);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

     }
}

TiendaVirtual_CarritoCompra/Views/Productos/Create.cshtml
@model TiendaVirtual_CarritoCompra.Models.Productos

@{
    ViewBag.Title = "Crear";
}

<h2>Crear</h2>

@*Html.BeginForm("Create", "Productos", FormMethod.Post, new { enctype = "multipart / form - data"})*@
@using (Html.BeginForm("Create", "Productos", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Productos</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Categoria, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.SelectedIdCategoria, Model.SelectListCategorias, "Selecciona categoría", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Categoria, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.PathImagen, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PathImagen, new { htmlAttributes = new { @class = "form-control", @type = "file" } })
            @Html.ValidationMessageFor(model => model.PathImagen, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PrecioUnidad, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PrecioUnidad, "Currency", new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PrecioUnidad, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Cantidad, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Cantidad, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Cantidad, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Crear" class="btn btn-default" />
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10 text-success">
            @ViewBag.FileStatus
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Volver a la Lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
}

TiendaVirtual_CarritoCompra/Views/Productos/Delete.cshtml
@model TiendaVirtual_CarritoCompra.Models.Productos

@{
    ViewBag.Title = "Eliminar";
}

<h2>Eliminar</h2>

<h3>¿Está seguro de querer eliminar el producto?</h3>
<div>
    <h4>Productos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PathImagen)
        </dt>

        <dd>
            <img src="@Url.Content("~/Content/Images/" + @Path.GetFileName(@Model.PathImagen))" width="150" height="150" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PrecioUnidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrecioUnidad)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-default" /> |
            @Html.ActionLink("Volver a la Lista", "Index")
        </div>
    }
</div>

TiendaVirtual_CarritoCompra/Views/Productos/Details.cshtml
@model TiendaVirtual_CarritoCompra.Models.Productos

@{
    ViewBag.Title = "Detalle";
}

<h2>Detalle</h2>

<div>
    <h4>Productos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PathImagen)
        </dt>

        <dd>
            <img src="@Url.Content("~/Content/Images/" + @Path.GetFileName(@Model.PathImagen))" width="150" height="150" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PrecioUnidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrecioUnidad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Categoria)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categoria.Nombre)
        </dd>

    </dl>
</div>
<p>
    @if (User.Identity.Name.Equals("admin1@correo.es"))
    {
        @Html.ActionLink("Editar", "Edit", new { id = Model.Id })
        <span>|</span>
    }

    @Html.ActionLink("Añadir a Carrito", "Add", "Carrito", new { id = Model.Id }, null) |
    @Html.ActionLink("Volver a la Lista", "Index")
</p>

TiendaVirtual_CarritoCompra/Views/Productos/Edit.cshtml
@model TiendaVirtual_CarritoCompra.Models.Productos

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Productos</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Categoria, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Categoria.Nombre, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })            
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PathImagen, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <img src="@Url.Content("~/Content/Images/" + @Path.GetFileName(@Model.PathImagen))" width="150" height="150" />          
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PrecioUnidad, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PrecioUnidad, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PrecioUnidad, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Cantidad, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Cantidad, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Cantidad, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Guardar" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Volver a la Lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TiendaVirtual_CarritoCompra/Views/Productos/Index.cshtml
@model IEnumerable<TiendaVirtual_CarritoCompra.Models.Productos>

@{
    ViewBag.Title = "Productos";
}

<h2>Productos</h2>

@if (User.Identity.Name.Equals("admin1@correo.es"))
{
<p>
    @Html.ActionLink("Crear Nuevo", "Create")
</p>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PathImagen)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PrecioUnidad)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descripcion)
        </td>
        <td>
            <img src="@Url.Content("~/Content/Images/" + @Path.GetFileName(item.PathImagen))" width="75" height="75"/>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PrecioUnidad)
        </td>
        <td>
            @if (item.Cantidad == 0)
            {
                @Html.Label("No disponible")
            }
            @if (item.Cantidad > 0)
            {
                if (User.Identity.Name.Equals("admin1@correo.es"))
                {
                    @Html.ActionLink("Editar", "Edit", new { id = item.Id })
                    <span> |</span>
                    @Html.ActionLink("Eliminar", "Delete", new { id = item.Id })
                    <span> |</span>
                }
                @Html.ActionLink("Detalle", "Details", new { id = item.Id })
                <span> |</span>
                @Html.ActionLink("Añadir a Carrito", "Add", "Carrito", new { id = item.Id }, null)
            }
        </td>
    </tr>
}

</table>