TiendaVirtual_CarritoCompra/Models/Carrito.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaVirtual_CarritoCompra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrito
    {
        public int Id { get; set; }
        public int Cantidad { get; set; }
        public string UsuarioId { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public decimal PrecioTotal { get; set; }
    
        public virtual Productos Productos { get; set; }
    }
}

TiendaVirtual_CarritoCompra/Controllers/CarritoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TiendaVirtual_CarritoCompra.Models;

namespace TiendaVirtual_CarritoCompra.Controllers
{
    public class CarritoController : Controller
    {
        private TiendaVirtualCCEntities db = new TiendaVirtualCCEntities();

        private const int minCantidad = 2;

        // GET: CarritoCompra
        public ActionResult Index()
        {

            ViewBag.TotalProductos = SumaTotalProductosCarrito();
            return View((List<CarritoCompra>)HttpContext.Session["CARRITO"]);
        }

        // GET: Carrito/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            List<CarritoCompra> carritoCompra = (List<CarritoCompra>)HttpContext.Session["CARRITO"];
            int index = ExisteProductoEnCarrito(id);
            CarritoCompra carrito = carritoCompra[index];
            if (carrito == null)
            {
                return HttpNotFound();
            }
            return View(carrito);
        }

        // GET: Carrito/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            List<CarritoCompra> carritoCompra = (List<CarritoCompra>)HttpContext.Session["CARRITO"];
            int index = ExisteProductoEnCarrito(id);
            CarritoCompra carrito = carritoCompra[index];
            if (carrito == null)
            {
                return HttpNotFound();
            }
            return View(carrito);
        }


        // POST: Carrito/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            List<CarritoCompra> carritoCompra = (List<CarritoCompra>)HttpContext.Session["CARRITO"];
            int index = ExisteProductoEnCarrito(id);
            CarritoCompra carrito = carritoCompra[index];
            UpdateStockProductoRemoveCarrito(carrito);
            carritoCompra.Remove(carrito);
            if (carritoCompra.Any())
            {
                HttpContext.Session["CARRITO"] = carritoCompra;
            }
            else
            {
                HttpContext.Session["CARRITO"] = null;
            }           

            return RedirectToAction("Index");
        }

        // GET: Carrito
        public ActionResult Add(int id)
        {
            HttpSessionStateBase session = HttpContext.Session;

            string usuarioId = GetUsuarioId();
            CarritoCompra carrito = GetCarrito(id, usuarioId);

            if (session["CARRITO"] == null)
            {
                List<CarritoCompra> carritoCompra = new List<CarritoCompra>();
                carritoCompra.Add(carrito);
                session["CARRITO"] = carritoCompra;
            }
            else
            {
                List<CarritoCompra> carritoCompra = (List<CarritoCompra>)session["CARRITO"];
                int index = ExisteProductoEnCarrito(id);
                if (index != -1)
                {
                    carritoCompra[index].Cantidad++;
                    carritoCompra[index].PrecioTotal = carritoCompra[index].Cantidad * carritoCompra[index].Productos.PrecioUnidad;
                }
                else
                {
                    carritoCompra.Add(carrito);
                }
                session["CARRITO"] = carritoCompra;
            }

            UpdateStockProductoAddCarrito(id);

            return RedirectToAction("Index");
        }

        private void UpdateStockProductoAddCarrito(int id)
        {
            Productos productos = GetProductoById(id);
            productos.Cantidad = productos.Cantidad - 1;
            if (productos.Cantidad.Equals(minCantidad)) {
                Stocks stocks = new Stocks {
                    Productos = productos
                };                
                db.Stocks.Add(stocks);
                productos.Stock = stocks;
            }
            db.SaveChanges();
        }

        private void UpdateStockProductoRemoveCarrito(CarritoCompra carrito)
        {
            Productos productos = GetProductoById(carrito.Productos.Id);
            productos.Cantidad = productos.Cantidad + carrito.Cantidad;
            if (productos.Stock != null && productos.Cantidad > minCantidad)
            {                
                db.Stocks.Remove(productos.Stock);
                productos.Stock = null;
            }
            db.SaveChanges();
        }

        public CarritoCompra GetCarrito(int id, string usuarioId)
        {
            Random random = new Random();
            int idCarrito = random.Next(1, 1000);
            
            Productos producto = GetProductoById(id);
            return new CarritoCompra
            {
                Productos = producto,
                Id = idCarrito,
                FechaAlta = DateTime.Now,
                Cantidad = 1,
                UsuarioId = usuarioId,
                PrecioTotal = producto.PrecioUnidad * 1
            };

        }

        private Productos GetProductoById(int id)
        {
            return db.Productos.SingleOrDefault(
           p => p.Id == id);
        }

        private string GetUsuarioId()
        {
            HttpSessionStateBase session = HttpContext.Session;
            if (session["KEY_USER_ID"] == null)
            {
                if (!string.IsNullOrWhiteSpace(User.Identity.Name))
                {
                    session["KEY_USER_ID"] = User.Identity.Name;
                }
                else
                {
                    // Generate a new random GUID using System.Guid class.     
                    Guid tempCartId = Guid.NewGuid();
                    session["KEY_USER_ID"] = tempCartId.ToString();
                }
            }
            return session["KEY_USER_ID"].ToString();
        }

        private int ExisteProductoEnCarrito(int? id)
        {
            HttpSessionStateBase session = HttpContext.Session;
            List<CarritoCompra> carritoCompra = (List<CarritoCompra>)session["CARRITO"];
            for (int i = 0; i < carritoCompra.Count; i++)
            {
                if (carritoCompra[i].Productos.Id.Equals(id))
                    return i;
            }
            return -1;
        }

        private decimal SumaTotalProductosCarrito()
        {
            HttpSessionStateBase session = HttpContext.Session;
            decimal totalSuma = 0;
            List<CarritoCompra> carritoCompra = (List<CarritoCompra>)session["CARRITO"];
            for (int i = 0; carritoCompra != null && i < carritoCompra.Count; i++)
            {
                totalSuma = totalSuma + carritoCompra[i].PrecioTotal;
            }
            return totalSuma;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TiendaVirtual_CarritoCompra/Controllers/PedidosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TiendaVirtual_CarritoCompra.Models;

namespace TiendaVirtual_CarritoCompra.Controllers
{
    public class PedidosController : Controller
    {
        private TiendaVirtualCCEntities db = new TiendaVirtualCCEntities();

        // GET: Pedidos
        public ActionResult Index()
        {
            string userId = HttpContext.Session["KEY_USER_ID"].ToString();
            var query = from p in db.Pedidos
                            where p.UsuarioId == userId
                            && p.Facturas == null
                            select p;

            List<Pedidos> pedidos = new List<Pedidos> {
                query.FirstOrDefault<Pedidos>()
            };

            if(pedidos!=null && !pedidos.Contains(null))
            {
                return View(pedidos);
            } else
            {
                return View(new List<Pedidos>());
            }            
        }

        // GET: Pedidos/Tramitar
        public ActionResult Tramitar()
        {
            List<CarritoCompra> carrito = (List<CarritoCompra>)HttpContext.Session["CARRITO"];

            int cantidad = SumaTotalCantidadCarrito(carrito);
            decimal totalProductos = SumaTotalProductosCarrito(carrito);
            string userId = HttpContext.Session["KEY_USER_ID"].ToString();

            Pedidos pedido = new Pedidos
            {
                Cantidad = cantidad,
                Fecha = DateTime.Now,
                Total = totalProductos,
                UsuarioId = userId
            };

            db.Pedidos.Add(pedido);
            db.SaveChanges();

            return RedirectToAction("Index");
        } 

        // GET: Pedidos/Cancel/5
        public ActionResult Cancel(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pedidos pedidos = db.Pedidos.Find(id);
            if (pedidos == null)
            {
                return HttpNotFound();
            }
            return View(pedidos);
        }

        // POST: Pedidos/Cancel/5
        [HttpPost, ActionName("Cancel")]
        [ValidateAntiForgeryToken]
        public ActionResult CancelConfirmed(int id)
        {            
            Pedidos pedidos = db.Pedidos.Find(id);
            db.Pedidos.Remove(pedidos);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        private decimal SumaTotalProductosCarrito(List<CarritoCompra> carritoCompra)
        {            
            decimal totalSuma = 0;            
            for (int i = 0; carritoCompra != null && i < carritoCompra.Count; i++)
            {
                totalSuma = totalSuma + carritoCompra[i].PrecioTotal;
            }
            return totalSuma;
        }

        private int SumaTotalCantidadCarrito(List<CarritoCompra> carritoCompra)
        {
            int totalCantidad = 0;
            for (int i = 0; carritoCompra != null && i < carritoCompra.Count; i++)
            {
                totalCantidad = totalCantidad + carritoCompra[i].Cantidad;
            }
            return totalCantidad;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TiendaVirtual_CarritoCompra/Controllers/ProductosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TiendaVirtual_CarritoCompra.Models;

namespace TiendaVirtual_CarritoCompra.Controllers
{
    public class ProductosController : Controller
    {
        private TiendaVirtualCCEntities db = new TiendaVirtualCCEntities();

        // GET: Productos
        public ActionResult Index()
        {
            return View(db.Productos.ToList());
        }

        // GET: Productos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Productos productos = db.Productos.Find(id);
            if (productos == null)
            {
                return HttpNotFound();
            }
            return View(productos);
        }

        // GET: Productos/Create
        [Authorize(Users = "admin1@correo.es")]
        public ActionResult Create()
        {            
            SelectList lstCategoriasSelectList = new SelectList(db.Categorias, "Id", "Nombre");

            Productos producto = new Productos
            {
                SelectListCategorias = lstCategoriasSelectList
            };

            return View(producto);
        }
        
        // POST: Productos/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Users = "admin1@correo.es")]
        public ActionResult Create([Bind(Include = "Id,Nombre,Descripcion,PathImagen,PrecioUnidad,SelectedIdCategoria,Cantidad")] Productos productos)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (Request.Files.Count > 0)
                    {
                        var file = Request.Files[0];
                        if (file != null && file.ContentLength > 0)
                        {
                            var fileName = Path.GetFileName(file.FileName);
                            var path = Path.Combine(Server.MapPath("~/Content/Images"), fileName);
                            file.SaveAs(path);
                            productos.PathImagen = fileName;
                            ViewBag.FileStatus = "Imagen subida correctamente.";
                        }

                    }
                    
                }
                catch (Exception)
                {
                    ViewBag.FileStatus = "Error mientras se subía el fichero."; ;
                }
                productos.Categoria = db.Categorias.Find(productos.SelectedIdCategoria);                
                db.Productos.Add(productos);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(productos);
        }

        // GET: Productos/Edit/5
        [Authorize(Users = "admin1@correo.es")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Productos productos = db.Productos.Find(id);
            if (productos == null)
            {
                return HttpNotFound();
            }
            return View(productos);
        }

        // POST: Productos/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Users = "admin1@correo.es")]
        public ActionResult Edit([Bind(Include = "Id,Nombre,Descripcion,PrecioUnidad,Cantidad")] Productos productos)
        {
            Productos producto = db.Productos.Find(productos.Id);
            producto.Nombre = productos.Nombre;
            producto.Descripcion = productos.Descripcion;
            producto.PrecioUnidad = productos.PrecioUnidad;
            producto.Cantidad = productos.Cantidad;
            db.SaveChanges();
            return RedirectToAction("Index");     
        }

        // GET: Productos/Delete/5
        [Authorize(Users = "admin1@correo.es")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Productos productos = db.Productos.Find(id);
            if (productos == null)
            {
                return HttpNotFound();
            }
            return View(productos);
        }

        // POST: Productos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Users = "admin1@correo.es")]
        public ActionResult DeleteConfirmed(int id)
        {
            Productos productos = db.Productos.Find(id);
            db.Productos.Remove(productos);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

     }
}

TiendaVirtual_CarritoCompra/Views/Carrito/Delete.cshtml
@model TiendaVirtual_CarritoCompra.Models.CarritoCompra

@{
    ViewBag.Title = "Eliminar";
}

<h2>Eliminar</h2>

<h3>¿Está seguro de querer eliminar este artículo del carrito?</h3>
<div>
    <h4>Carrito</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Productos.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Productos.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Productos.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Productos.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Productos.PathImagen)
        </dt>

        <dd>
            <img src="@Url.Content("~/Content/Images/" + @Path.GetFileName(@Model.Productos.PathImagen))" width="150" height="150" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cantidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cantidad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PrecioTotal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrecioTotal)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-default" /> |
            @Html.ActionLink("Volver al carrito", "Index")
        </div>
    }
</div>

TiendaVirtual_CarritoCompra/Views/Carrito/Details.cshtml
@model TiendaVirtual_CarritoCompra.Models.CarritoCompra

@{
    ViewBag.Title = "Detalle";
}

<h2>Detalle</h2>

<div>
    <h4>Carrito</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Productos.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Productos.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Productos.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Productos.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Productos.PathImagen)
        </dt>

        <dd>
            <img src="@Url.Content("~/Content/Images/" + @Path.GetFileName(@Model.Productos.PathImagen))" width="150" height="150" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cantidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cantidad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PrecioTotal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrecioTotal)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Eliminar", "Delete", new { id = Model.Productos.Id }) |
    @Html.ActionLink("Volver al carrito", "Index")
</p>

TiendaVirtual_CarritoCompra/Views/Carrito/Index.cshtml
@model IEnumerable<TiendaVirtual_CarritoCompra.Models.CarritoCompra>

@{
    ViewBag.Title = "Carrito";
    var IsCarritoEmpty = Session["CARRITO"] == null;
}
<h2>Su Carrito de la Compra</h2>

@if (IsCarritoEmpty)
{
    <h3>No tiene artículos en su carrito de la compra</h3>
}
@if (!IsCarritoEmpty)
{
    <p>
        @Html.ActionLink("Tramitar pedido", "Tramitar", "Pedidos")
    </p>

    <table class="table">
        <tr>            
            <th>
                @Html.DisplayNameFor(model => model.Productos.PathImagen)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Productos.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cantidad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PrecioTotal)
            </th>            
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>                
                <td>
                    <img src="@Url.Content("~/Content/Images/" + @Path.GetFileName(item.Productos.PathImagen))" width="75" height="75" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Productos.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cantidad)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PrecioTotal)
                </td>                
                <td>
                    @Html.ActionLink("Detalle", "Details", new { id = item.Productos.Id }) |
                    @Html.ActionLink("Eliminar", "Delete", new { id = item.Productos.Id }) |
                    @Html.ActionLink("Volver a la Lista", "Index", "Productos")
                </td>
            </tr>
        }

    </table>

    <hr />

    <div>
        <dl class="dl-horizontal">
            <dt>
                Total de productos:
            </dt>

            <dd>
                @((ViewBag.TotalProductos).ToString("C2"))
            </dd>

            <dt>
                Gastos de envío:
            </dt>

            <dd>
                0,00 €
            </dd>

            <dt>
                TOTAL:
            </dt>

            <dd>
                @((ViewBag.TotalProductos).ToString("C2"))
            </dd>

        </dl>
    </div>
}