TiendaVirtual_CarritoCompra/Models/Pedidos.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaVirtual_CarritoCompra.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Pedidos
    {
        public int Id { get; set; }

        [Display(Name = "Cliente")]
        public string UsuarioId { get; set; }

        public System.DateTime Fecha { get; set; }
        public int Cantidad { get; set; }

        [DataType(DataType.Currency)]
        [Display(Name = "Precio Total Pedido")]
        public decimal Total { get; set; }

        public virtual Facturas Facturas { get; set; }
    }
}

TiendaVirtual_CarritoCompra/Controllers/FacturasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TiendaVirtual_CarritoCompra.Models;

namespace TiendaVirtual_CarritoCompra.Controllers
{
    public class FacturasController : Controller
    {
        private TiendaVirtualCCEntities db = new TiendaVirtualCCEntities();

        // GET: Facturas
        public ActionResult Index(Pedidos pedido)
        {
            string userId = HttpContext.Session["KEY_USER_ID"].ToString();

            var query = from fc in db.Facturas
                        where fc.UsuarioId == userId
                        && fc.Pedido.Id == pedido.Id
                        select fc;

            List < Facturas > facturas = new List<Facturas> {
                query.FirstOrDefault<Facturas>()
            };

            HttpContext.Session["CARRITO"] = null;

            return View(facturas);
        }

        // GET: Facturas/GenerateBill/5
        public ActionResult GenerateBill(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pedidos pedidos = db.Pedidos.Find(id);
            if (pedidos == null)
            {
                return HttpNotFound();
            }
            Facturas factura = new Facturas
            {
                Importe = pedidos.Total,
                UsuarioId = pedidos.UsuarioId,
                Pedido = pedidos
            };
            db.Facturas.Add(factura);
            pedidos.Facturas = factura;
            db.SaveChanges();

            return RedirectToAction("Index", pedidos);           
        } 

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TiendaVirtual_CarritoCompra/Controllers/PedidosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TiendaVirtual_CarritoCompra.Models;

namespace TiendaVirtual_CarritoCompra.Controllers
{
    public class PedidosController : Controller
    {
        private TiendaVirtualCCEntities db = new TiendaVirtualCCEntities();

        // GET: Pedidos
        public ActionResult Index()
        {
            string userId = HttpContext.Session["KEY_USER_ID"].ToString();
            var query = from p in db.Pedidos
                            where p.UsuarioId == userId
                            && p.Facturas == null
                            select p;

            List<Pedidos> pedidos = new List<Pedidos> {
                query.FirstOrDefault<Pedidos>()
            };

            if(pedidos!=null && !pedidos.Contains(null))
            {
                return View(pedidos);
            } else
            {
                return View(new List<Pedidos>());
            }            
        }

        // GET: Pedidos/Tramitar
        public ActionResult Tramitar()
        {
            List<CarritoCompra> carrito = (List<CarritoCompra>)HttpContext.Session["CARRITO"];

            int cantidad = SumaTotalCantidadCarrito(carrito);
            decimal totalProductos = SumaTotalProductosCarrito(carrito);
            string userId = HttpContext.Session["KEY_USER_ID"].ToString();

            Pedidos pedido = new Pedidos
            {
                Cantidad = cantidad,
                Fecha = DateTime.Now,
                Total = totalProductos,
                UsuarioId = userId
            };

            db.Pedidos.Add(pedido);
            db.SaveChanges();

            return RedirectToAction("Index");
        } 

        // GET: Pedidos/Cancel/5
        public ActionResult Cancel(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pedidos pedidos = db.Pedidos.Find(id);
            if (pedidos == null)
            {
                return HttpNotFound();
            }
            return View(pedidos);
        }

        // POST: Pedidos/Cancel/5
        [HttpPost, ActionName("Cancel")]
        [ValidateAntiForgeryToken]
        public ActionResult CancelConfirmed(int id)
        {            
            Pedidos pedidos = db.Pedidos.Find(id);
            db.Pedidos.Remove(pedidos);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        private decimal SumaTotalProductosCarrito(List<CarritoCompra> carritoCompra)
        {            
            decimal totalSuma = 0;            
            for (int i = 0; carritoCompra != null && i < carritoCompra.Count; i++)
            {
                totalSuma = totalSuma + carritoCompra[i].PrecioTotal;
            }
            return totalSuma;
        }

        private int SumaTotalCantidadCarrito(List<CarritoCompra> carritoCompra)
        {
            int totalCantidad = 0;
            for (int i = 0; carritoCompra != null && i < carritoCompra.Count; i++)
            {
                totalCantidad = totalCantidad + carritoCompra[i].Cantidad;
            }
            return totalCantidad;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TiendaVirtual_CarritoCompra/Views/Pedidos/Cancel.cshtml
@model TiendaVirtual_CarritoCompra.Models.Pedidos

@{
    ViewBag.Title = "Delete";
}

<h2>Cancelar pedido</h2>

<h3>¿Está seguro de querer cancelar el pedido?</h3>
<div>
    <h4>Pedidos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UsuarioId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UsuarioId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cantidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cantidad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Cancelar" class="btn btn-default" /> |
            @Html.ActionLink("Volver a pedido", "Index")
        </div>
    }
</div>

TiendaVirtual_CarritoCompra/Views/Pedidos/Delete.cshtml
@model TiendaVirtual_CarritoCompra.Models.Pedidos

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pedidos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UsuarioId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UsuarioId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cantidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cantidad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TiendaVirtual_CarritoCompra/Views/Pedidos/Index.cshtml
@model IEnumerable<TiendaVirtual_CarritoCompra.Models.Pedidos>

@{
    ViewBag.Title = "Pedido";
}

<h2>Pedido</h2>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.UsuarioId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fecha)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cantidad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Total)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.UsuarioId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Fecha)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cantidad)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Total)
                </td>
                <td>
                    @Html.ActionLink("Cancelar", "Cancel", new { id = item.Id }) |
                    @Html.ActionLink("Continuar Pago", "GenerateBill", "Facturas", new { id = item.Id }, null)
                </td>
            </tr>
        }

    </table>